version: '3'

services: 
    api:
        container_name: api
        build: 
            context: ./api
        ports:
            - "8080:8080"
        stdin_open: true
        volumes: 
            - './api:/usr/src/app'
            - '/usr/src/app/node_modules'
        links:
            - mongo
            - redis
        env_file:
            - .env

    client:
        container_name: client
        build: 
            context: ./client
        stdin_open: true
        volumes: 
            - './client:/usr/src/app'
            - '/usr/src/app/node_modules'
            - '/usr/src/app/.next'
        ports: 
            - "3000:3000"
            - "9229:9229"
        links:
            - api
        env_file:
            - .env

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
    
    mongoex:
        container_name: mongoex
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - mongo
        links:
            - mongo
        
    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=redis
        ports:
            - "8082:8081"
        links:
            - mongo

    redis:
        image: redis:alpine
        ports:
        - "6379:6379"

   