version: '3.7'

services:

    api-prod:
        container_name: api
        build: 
            context: ./api
            dockerfile: Dockerfile.prod
        ports:
            - "8080:8080"
        links:
            - mongo
            - redis
        env_file:
            - .env

    client:
        container_name: client
        build: 
            context: ./client
            dockerfile: Dockerfile.prod
        links:
            - api
        env_file:
            - .env

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"

    redis:
        image: redis:alpine
        ports:
        - "6379:6379"

    nginx-client:
        build: ./client/nginx
        ports:
        - 80:80
